name: ci cd

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci_cd:
    runs-on: ubuntu-18.04
    name: Continuous Integration/Continuous Deployment
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # necessary for capturing 'version' below

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm test
      - run: npm run build

      - name: Capture version
        if: github.ref == 'refs/heads/main'
        id: version
        run: |
          echo "::set-output name=TEXT::$(git describe --always --long)"
          echo "::set-output name=COMMITISH::$(git rev-parse HEAD)"
          echo "::set-output name=DATE::$(git rev-parse HEAD)"

      - name: Save version
        if: github.ref == 'refs/heads/main'
        run: |
          echo '{ "text": "${{ steps.version.outputs.TEXT }}", "commitish": "${{ steps.version.outputs.COMMITISH }}", "date": "${{ steps.version.outputs.DATE }}" }' > ./dist/version.json

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
