name: add to project

on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened
env:
  MY_GITHUB_TOKEN: ${{ secrets.ORG_LEVEL_PM_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Add NEW issues to Project
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event == 'issue'
        with:
          project: 'https://github.com/orgs/kollavarsham/projects/1'
          column_name: 'To do'

      - name: Add NEW issues to Project
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event == 'pull_request'
        with:
          project: 'https://github.com/orgs/kollavarsham/projects/1'
          column_name: 'In progress'
