name: add to project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
env:
  MY_GITHUB_TOKEN: ${{ secrets.ORG_LEVEL_PM_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Add to Project
    steps:
      - name: Add issues/PRs to Project
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/orgs/kollavarsham/projects/1'
